name: covid-rnaseq
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python=3.14
  - snakemake-minimal>=7
  - r-base>=4.2
  - bioconductor-geoquery
  - bioconductor-deseq2
  - bioconductor-clusterprofiler
  - bioconductor-org.hs.eg.db
  - bioconductor-enhancedvolcano
  - r-pheatmap
  - r-ggplot2
